const Images = {
  loader1: new URL("./svg/loader1.svg", import.meta.url).href,
  circleLoader: new URL("./png/circle-preloader.gif", import.meta.url).href,
  preloader: new URL("./png/preloader.gif", import.meta.url).href,
  logo_2: new URL("./logo-2.svg", import.meta.url).href,
  logo_1_png: new URL("./logo_1.png", import.meta.url).href,
  logo_2_png: new URL("./logo_2.png", import.meta.url).href,
  logo_3_png: new URL("./logo_3.png", import.meta.url).href,
  colorLogo: new URL("./svg/color-logo.svg", import.meta.url).href,
  loginBanner: new URL("./png/auth/login-banner.png", import.meta.url).href,
  power_icon: new URL("./svg/power.svg", import.meta.url).href,
  eye_open_icon: new URL("./svg/eye_open_icon.svg", import.meta.url).href,
  eye_closed_icon: new URL("./svg/eye_closed_icon.svg", import.meta.url).href,
  loader_btn: new URL("./png/loader1.gif", import.meta.url).href,
  slide_1: new URL("./png/slider/slide-1.png", import.meta.url).href,
  popular_1: new URL("./png/popular/popular-1.png", import.meta.url).href,
  popular_2: new URL("./png/popular/popular-2.png", import.meta.url).href,
  popular_3: new URL("./png/popular/popular-3.png", import.meta.url).href,
  popular_4: new URL("./png/popular/popular-4.png", import.meta.url).href,
  popular_5: new URL("./png/popular/popular-5.png", import.meta.url).href,
  arrow_circle_right: new URL("./svg/arrow-circle-right.svg", import.meta.url).href,
  arrow_circle_left: new URL("./svg/arrow-circle-left.svg", import.meta.url).href,
  room_pic_1: new URL("./png/room/room-1.jpg", import.meta.url).href,
  room_pic_2: new URL("./png/room/room-2.jpg", import.meta.url).href,
  room_pic_3: new URL("./png/room/room-3.jpg", import.meta.url).href,
  room_default: new URL("./png/room/default.jpg", import.meta.url).href,
  empty_1: new URL("./svg/empty-1.svg", import.meta.url).href,
  trash_img: new URL("./svg/trash-img.svg", import.meta.url).href,
  add_comment: new URL("./svg/add-comment.svg", import.meta.url).href,
  add_review: new URL("./svg/add-review.svg", import.meta.url).href,
  book_banner: new URL("./png/book-room.png", import.meta.url).href,
  // menu items
  catug_icon: new URL("./svg/sidebar/catug.svg", import.meta.url).href,
  date_icon: new URL("./svg/sidebar/date.svg", import.meta.url).href,
  home_icon: new URL("./svg/sidebar/home.svg", import.meta.url).href,
  lock_icon: new URL("./svg/sidebar/lock.svg", import.meta.url).href,
  logout_icon: new URL("./svg/sidebar/logout.svg", import.meta.url).href,
  users_icon: new URL("./svg/sidebar/users.svg", import.meta.url).href,
  deleteImg: new URL("./svg/delete-img.svg", import.meta.url).href,
  deleteIcon: new URL("./svg/delete-icon.svg", import.meta.url).href,
  lockIcon: new URL("./svg/sidebar/lock.svg", import.meta.url).href,
  ads_icon: new URL("./svg/sidebar/ads.svg", import.meta.url).href,
  defaultImage: new URL("./svg/default-image.svg", import.meta.url).href,
  small_logo: new URL("./png/sidebar-logo.png", import.meta.url).href,
  // room items
  ic_icon: new URL("./svg/room/ic_ac.svg", import.meta.url).href,
  bathroom_icon: new URL("./svg/room/ic_bathroom.svg", import.meta.url).href,
  bedroom_icon: new URL("./svg/room/ic_bedroom.svg", import.meta.url).href,
  diningroom_icon: new URL("./svg/room/ic_diningroom.svg", import.meta.url).href,
  kulkas_icon: new URL("./svg/room/ic_kulkas.svg", import.meta.url).href,
  livingroom_icon: new URL("./svg/room/ic_livingroom.svg", import.meta.url).href,
  tv_icon: new URL("./svg/room/ic_tv.svg", import.meta.url).href,
  wifi_icon: new URL("./svg/room/ic_wifi.svg", import.meta.url).href,
  //social
  google_icon: new URL("./svg/google-icon.svg", import.meta.url).href,

  uploadIcon: new URL("./json/upload.json", import.meta.url).href,
};

export default Images;
